site_name: Dev Docs
nav:
  - Introduction: "index.md"
  - Server Management:
    - Introduction: "server-management/introduction.md"
    - Security:
      - Secure Linux Server: "server-management/security/secure-linux-server.md"
      - DDOS: "server-management/security/ddos.md"
      - SSL/TSL: 
        - Setup: "server-management/security/ssl/ssl-setup.md"
        - Install Certificate: "server-management/security/ssl/install-ca-certificate.md"
    - Web Servers:
      - Apache: "server-management/web-servers/apache/concurrency.md"
    - Kubernetes: 
      - Setup: "server-management/kubernetes/setup.md"
      - Image Deployment: "server-management/kubernetes/image-deployment.md"
  - Database Management:
    - Postgres:
      - Installation: "database-management/postgre/installation.md"
      - Replication: "database-management/postgre/replication.md"